#cloud-config
package_upgrade: true
packages:
- httpd
write_files:
  - content: |
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <title>Sample Deployment</title>
          <style>
            body {
              color: #ffffff;
              background-color: #0188cc;
              font-family: Arial, sans-serif;
              font-size: 14px;
            }
            
            h1 {
              font-size: 500%;
              font-weight: normal;
              margin-bottom: 0;
            }
            
            h2 {
              font-size: 200%;
              font-weight: normal;
              margin-bottom: 0;
            }
          </style>
        </head>
        <body>
          <div align="center">
            <h1>WELCOME</h1>
            <h2>This is an Assignment</h2>
          </div>
        </body>
        </html>
    
    path: /var/www/html/index.html


runcmd:
- systemctl start httpd
- systemctl enable httpd
- chkconfig httpd on